apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: jiaf-dashboards-updater
  namespace: argo-cd
spec:
  namespace: argo-cd
  commonUpdateSettings:
    updateStrategy: "latest"
    forceUpdate: false
    pullSecret: "pullsecret:default/regcred"
  applicationRefs:
    - namePattern: "jiaf-dashboards*"
      images:
        - alias: "jiaf-dashboards"
          imageName: "ghcr.io/ocha-hpcs/jiaf-dashboards"
