apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: jiaf-dashboards-updater
spec:
  namespace: argocd
  commonUpdateSettings:
    updateStrategy: "latest"
    forceUpdate: false
  applicationRefs:
    - namePattern: "jiaf-dashboards*"
      images:
        - alias: "jiaf-dashboards"
          imageName: "ghcr.io/ocha-hpcs/jiaf-dashboards"
