apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: global-config
    literals:
      - hostname=jiaf-dashboards.hpcs-cluster.cyruspellet.com

vars:
  - name: HOSTNAME
    objref:
      kind: ConfigMap
      name: global-config
      apiVersion: v1
    fieldref:
      fieldpath: data.hostname
